#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2016 OpenWrt.org

START=90

start() {
	echo "Setting up Zipit Z2 LED's..."
	echo "mmc0" > /sys/class/leds/z2:green:charged/trigger
	echo "Z2-charging-blink-full-solid" > /sys/class/leds/z2\:amber\:charging/trigger
	if [ "$(cat /sys/class/power_supply/Z2/status)" == "Charging" ]; then
		echo "255" > /sys/class/leds/z2:amber:charging/brightness
	fi
}

boot() {
	start
}

