#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2016 OpenWrt.org

START=90

start() {
	echo "Setting up Zipit Z2 LED's..."
	echo "mmc0" > /sys/class/leds/z2\:green\:wifi/trigger
	echo "Z2-full" > /sys/class/leds/z2\:green\:charged/trigger
	echo "Z2-charging" > /sys/class/leds/z2\:amber\:charging/trigger
	STAT=`cat /sys/class/power_supply/Z2/status)`
	if [ "$STAT" == "Charging" ]; then
		echo "255" > /sys/class/leds/z2\:amber\:charging/brightness
	elif [ "$STAT" == "Full" ]; then
		echo "255" > /sys/class/leds/z2\:green\:charged/brightness
	fi
}

boot() {
	start
}

